Repository corona-warn-app/cwa-verification-portal, pull requests merged in 2020-06, with the labels that each got.

#76 fix: cross site forgery
  .gitignore
  src/main/java/app/coronawarn/verification/portal/controller/VerificationPortalController.java
Labels: bug, security

#73 feat: cipher
  src/main/java/app/coronawarn/verification/portal/VerificationPortalApplication.java
Labels: enhancement

#78 fix: increase test coverage
  pom.xml
  src/test/java/app/coronawarn/verification/portal/controller/VerificationPortalControllerTest.java
  src/test/java/app/coronawarn/verification/portal/service/TeleTanServiceTest.java
Labels: code improvement, implemented

#77 fix: integration-JWT
  src/main/java/app/coronawarn/verification/portal/client/VerificationServerClient.java
  src/main/java/app/coronawarn/verification/portal/service/TeleTanService.java
  src/test/java/app/coronawarn/verification/portal/service/TeleTanServiceTest.java
Labels: bug, implemented

#83 fix: Update release to 1.0.1 in pom.xml
  pom.xml
Labels: enhancement

#79 Minor code quality improvements
  src/main/java/app/coronawarn/verification/portal/VerificationPortalApplication.java
  src/main/java/app/coronawarn/verification/portal/client/VerificationServerClientConfig.java
  src/main/java/app/coronawarn/verification/portal/controller/VerificationPortalController.java
  src/main/java/app/coronawarn/verification/portal/exception/VerificationPortalException.java
  src/main/java/app/coronawarn/verification/portal/service/TeleTanService.java
Labels: code improvement

#84 Set-Cookie SameSite
  pom.xml
  src/main/java/app/coronawarn/verification/portal/SecurityConfig.java
Labels: implemented

#82 feat: add password ändern button
  src/main/java/app/coronawarn/verification/portal/controller/VerificationPortalController.java
  src/main/resources/application.yml
  src/main/resources/static/logout.js
  src/main/resources/static/teletan.css
  src/main/resources/templates/start.html
  src/main/resources/templates/teletan.html
Labels: enhancement, implemented
