Repository corona-warn-app/cwa-verification-portal, pull requests merged in 2020-07, with the labels that each got.

#88 fix: definition of teleTAN
  docs/architecture-overview.md
Labels: bug

#91 Update CODEOWNERS
  CODEOWNERS
Labels: documentation

#86 Host header validation
  pom.xml
  src/main/java/app/coronawarn/verification/portal/SecurityConfig.java
  src/main/java/app/coronawarn/verification/portal/VerificationPortalHttpFilter.java
  src/main/resources/application.yml
  src/test/java/app/coronawarn/verification/portal/VerificationPortalHttpFilterTest.java
Labels: in progress, security

#85 fix: enable container scanning
  Dockerfile
  scripts/Dpkg.java
Labels: bug

#89 fix: Implemented correct forwarding of server side 429 HTTP error
  src/main/java/app/coronawarn/verification/portal/controller/ServerRateLimitationException.java
  src/main/java/app/coronawarn/verification/portal/controller/VerificationPortalController.java
  src/main/java/app/coronawarn/verification/portal/controller/VerificationPortalErrorController.java
  src/test/java/app/coronawarn/verification/portal/controller/VerificationPortalControllerTest.java
Labels: bug
